### PR TITLE
Add implicit block and ignorable declarations in make-method-lambda.

### PR DESCRIPTION
**Pull request by marcoheisig**
According to the spec, every method body is enclosed in an implicit block
of the same name as the function.  Furthermore, for convenience, most
implementations declare all required arguments of a method as ignorable.
Prior to this commit, the implicit block and the ignorable declarations
were added as part of the expansion of closer-mop:defmethod, and before
supplying the lambda to make-method-lambda.  However, SBCL and ABCL do not
use the defmethod macro of closer-mop, but fall back to cl:defmethod.  As a
result, neither the implicit block, nor ignorable declarations were added
on SBCL and ABCL at all.  The reason why this bug was not detected earlier
is that this version of make-method-lambda is only used for custom generic
functions and methods.

This commit attempts to make the behavior of defmethod and
make-method-lambda uniform and correct across all implementation.  The
method body is now not at all manipulated by defmethod, but only by
make-method-lambda.

This commit fixes issue #15.

### CODE REVIEW

**Comment by Hexstream** [comment]
Sounds like a great fix! Thank you. I think the [CLOS MOP spec](https://clos-mop.hexstreamsoft.com/) could have been clearer about the handling of [defmethod](http://www.lispworks.com/documentation/HyperSpec/Body/m_defmet.htm)'s implicit block in [make-method-lambda](https://clos-mop.hexstreamsoft.com/generic-functions-and-methods/#make-method-lambda), which is probably why this problem had been overlooked.

**Comment by pcostanza** [comment]
Hi,
This looks mostly very good. I have three small issues:

1) nil is actually a valid generic function name according to CLOS MOP, so block-name shouldn't fail on this. ;)

2) A required parameter should only be ignorable when it is explicitly specialized. When it is only implicitly specialized to t, you might still get the warning according to ANSI CL. ANSI CL indeed says "might", so we could decide not to warn on them either. Any opinions on this?

3) I would still like to test this, because I'm a bit worried that this might clash with how defmethod is handled in various CL implementations. I'll do that ASAP. (The easter weekend gives me a bit of time. :)

Anyway, thanks a lot for the great work and for spotting this.

Pascal

**Comment by Hexstream** [comment]
> A required parameter should only be ignorable when it is explicitly specialized. When it is only implicitly specialized to t, you might still get the warning according to ANSI CL. ANSI CL indeed says "might", so we could decide not to warn on them either. Any opinions on this?

Good question, I can only say that I really hate having to babysit CCL about its adoption of the stricter interpretation. I don't see any value in these meaningless warnings.

**Comment by marcoheisig** [comment]
Let me think about these issues:

1. Heh, you are right.  According to the spec, the return value of generic-function-name is a function name or nil.

2. I'd prefer having all required arguments declared ignorable, irrespective of whether they have an explicit specializer or not.  In practice, having to add either the explicit T specializer or the explicit ignorable declarations is annoying.  And if some expert programmers really want these warnings, they can still define their custom method class and have make-method-lambda rebind all required arguments :grin: 

3. Yes, it would be great if you could run some more elaborate tests.  So far, I only checked my solution on SBCL and CCL.

I have one more issue I'd like to discuss:

4. Currently, the name of the implicit block is derived from the name of the generic function prototype that is supplied to make-method-lambda.  I am not sure whether this is the least surprising thing to do.  An alternative would be to have defmethod bind the supplied method name to a special variable and use this value, and to fall back to the generic function name only if that variable is not bound.  This boils down to the question whether we can be sure that the name supplied to defmethod is always the name of the generic function that will be supplied as the first argument to make-method-lambda?

**Comment by Hexstream** [comment]
> 1. Heh, you are right. According to the spec, the return value of generic-function-name is a function name or nil.

Yes, of course. This is to support anonymous generic functions, instead of forcing you to generate a gensym. Same concept as class names, which can also be nil for anonymous classes. (I've never needed this yet, but I'm glad that this is supported.)

> 2. I'd prefer having all required arguments declared ignorable, irrespective of whether they have an explicit specializer or not. In practice, having to add either the explicit T specializer or the explicit ignorable declarations is annoying. And if some expert programmers really want these warnings, they can still define their custom method class and have make-method-lambda rebind all required arguments :grin:

It seems we have a consensus!

> 4. Currently, the name of the implicit block is derived from the name of the generic function prototype that is supplied to make-method-lambda. I am not sure whether this is the least surprising thing to do. [...]

I don't understand why you think this would be in any way surprising, to me that's clearly the logical thing to do. I don't understand why you want to involve a special variable in this.

**Comment by marcoheisig** [comment]
> > 1. Currently, the name of the implicit block is derived from the name of the generic function prototype that is supplied to make-method-lambda. I am not sure whether this is the least surprising thing to do. [...]
> 
> I don't understand why you think this would be in any way surprising, to me that's clearly the logical thing to do. I don't understand why you want to involve a special variable in this.

I am slightly worried because according to the specification of make-method-lambda, "The generic function and method the method function will be used with are not required to be the given ones."  It could be that the first argument of make-method-lambda has a different name than the defmethod form being processed.  And having a block name that is different from the name supplied to defmethod is probably an unwelcome surprise.

**Comment by Hexstream** [comment]
I see, but I'm a bit doubtful about "It could be that the first argument of make-method-lambda has a different name than the defmethod form being processed."

I think we should go with the straightforward way instead of trying to mitigate possibly imaginary problems. Advanced users for which this would be an actual problem can solve this easily with a make-method-lambda method for their custom method class, or other MOP-level customizations. I think there is a lot of potential for future improvements regarding generic functions.

**Comment by pcostanza** [comment]
I merged your pull request with minor changes.

**Pull request merged**
