### PR TITLE
use make-load-form for consifying specializer (works on CCL)

### PR DESCRIPTION
**Pull request by akssri**
Currently closer-mop does not allow the usage of meta-specializers, due to limitations in extract-specializers. The current change consifies specializer objects by calling make-load-form. This also seems to be inline with how SBCL handles things (I think). I'm not entirely sure how it's dealt with in AMOP.

### CODE REVIEW

**Comment by pcostanza** [comment]
I'm not sure I understand what you are trying to achieve. Make-load-form will not work like this in the general case. Class metaobjects should already be passed through (but are not wrapped in a make-load-form).

Are you looking for ensure-method? If not, could you provide a use case or an example?

Thanks,
Pascal

**Comment by akssri** [comment]
Ah, you're right; the ```make-load-form``` here is not necessary. The current method however does raise an error when passed an instance of a subclass of the specializer metaclass.

**Comment by pcostanza** [comment]
The reason for this is that neither ANSI CL nor the CLOS MOP specify what should happen when the specializer in a defmethod form is neither a class nor an eql specializer. There is actually language in both specifications that seem to suggest that classes and eql specializers are the only kinds of acceptable specializers. (The real issue is probably that you would have to find a way how to make the parser for specializers in defmethod forms extensible.) A workaround is always to just use add-method directly.

**Comment by akssri** [comment]
I haven't found explicit constructions of specializer meta-objects in AMOP, but it also doesn't explicitly restrict its use. Indeed, otherwise, the whole specializer abstract class would be superfluous. 

The reference implementation of ```extract-specializers``` (```analyze-lambda-list``` [AMOP, P.299]) in Closette has no such restriction, and neither does SBCL.

**Comment by pcostanza** [comment]
Sorry  for the delayed response, but I was worried about the potential impact such a change might have, especially because I recalled some CL implementations not having a generic specializer metaobject class in the first place (which is, alas, not true anymore). I now added this change and tested it against all supported CL implementations, and it doesn't seem to cause any problems. (However, I don't have a concrete test case, so there is no guarantee that this does what it's supposed to, it just became a bit more liberal in what kind of specializers it accepts.)

I hope this does what you need. Happy new year! :)

**Comment by akssri** [comment]
Thank you!

**Pull request closed without merging**
